# Generated by Django 4.2.1 on 2023-06-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('count', models.PositiveBigIntegerField(blank=True, default=1, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dostavka',
                'verbose_name_plural': 'Dostavka',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
