# Generated by Django 4.2.1 on 2023-06-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dostavka_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavka',
            name='status',
            field=models.CharField(choices=[('tayyorlanyapty', 'tayyorlanyapti'), ("tayyor bo'ldi", "tayyor bo'ldi")], default='tayyorlanyapti', max_length=100),
        ),
    ]
