# Generated by Django 4.2.1 on 2023-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dostavka_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostavka',
            name='status',
            field=models.CharField(choices=[('tayyorlanyapti', 'tayyorlanyapti'), ("tayyor bo'ldi", "tayyor bo'ldi")], default='tayyorlanyapti', max_length=100),
        ),
    ]
