# Generated by Django 4.2.1 on 2023-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dostavka_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostavka',
            name='all_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
